### ISSUE TITLE
TimescaleDB Toolkit?

### ISSUE THREAD

**Issue by Sh1ken** [clevyr/docker-cloudnativepg-timescale#16]
First of all, thanks for this repo! I got Timescale working on my Kubernetes cluster real quick. :)

Have you considered including the [TimescaleDB Toolkit](https://github.com/timescale/timescaledb-toolkit) also?

I'll have to implemented it either way so let me know if you're open to PRs.

Cheers.

**Comment by Felk** [comment]
I'm also interested in this. I've [read in Timescale's documentation](https://docs.timescale.com/self-hosted/latest/tooling/install-toolkit/#install-toolkit-on-self-hosted-timescaledb) that the toolkit is included in the official `timescale/timescaledb-ha` docker image, but I failed trying to get that one to work directly (https://github.com/cloudnative-pg/charts/issues/414).

**Comment by gabe565** [comment]
@Sh1ken @Felk Thanks for opening this, I wasn't aware of the Toolkit! I could investigate installing it, but it seems the latest CNPG version has added official support for TimescaleDB via the image catalog. I haven't tried it yet, but it look like it will use the official `timescale/timescaledb-ha` image. Take a look at https://github.com/cloudnative-pg/charts/pull/306 and let me know what you think

**Comment by Sh1ken** [comment]
Also @gabe565, I tried to add the `timescaledb_toolbox` following the same kind of config that you did for this chart: https://github.com/Sh1ken/docker-cloudnativepg-timescale/commit/4da8a12ee0e9041d69d2b81197167d4bc5f3d3e6.

Almost had success with it but had an issue retriving the correct package from packagecloud and that issue is still open: https://github.com/timescale/timescaledb-toolkit/issues/799#issuecomment-2375116105.

So, if you end up adding support for `timescaledb_toolkit` on your own, I wouldn't advice to follow this path.

**Comment by Felk** [comment]
Hey @gabe565 @Sh1ken, I indeed got CNPG working with the official TimescaleDB-HA-image by using the image catalog. I originally ran into some issues, which I described in more details here: https://github.com/cloudnative-pg/charts/issues/414

The short answer is: either use the cnpg helm chart (as described in the linked issue), or use an image catalog with the following additional tweaks:

- Set the UID and GID to 1000 as the timescaledb-ha image doesn't use the default user and group
- add `CREATE EXTENSION IF NOT EXISTS timescaledb_toolkot` to the init application SQL

So a minimal complete `Cluster` definition may look like this:
```yaml
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescale
  namespace: cnpg
spec:
  images:
    - major: 16
      image: timescale/timescaledb-ha:pg16
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: example
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: timescale
    major: 16
  instances: 1
  postgresql:
    shared_preload_libraries:
      - timescaledb
  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
        - CREATE EXTENSION IF NOT EXISTS timescaledb_toolkit;
  postgresGID: 1000
  postgresUID: 1000
```
